import { act, fireEvent, render, screen, within } from '@testing-library/react';
import { MemoryRouter } from 'react-router-dom';
import { beforeEach, expect, it, vi } from 'vitest';
const h = vi.hoisted(() => ({ Account: { list: vi.fn() }, Quote: { list: vi.fn() }, Policy: { list: vi.fn() }, Invoice: { list: vi.fn() }, Document: { list: vi.fn() } }));
vi.mock('aws-amplify/data', () => ({ generateClient: () => ({ models: h }) }));
import Overview from '../pages/dashboard/OverviewTab';
import { clearAsyncResourceCache } from '../lib/useAsyncResource';
beforeEach(() => { vi.clearAllMocks(); clearAsyncResourceCache(); });
it('shows account counts before quotes arrive, isolates policy failure, and does not load agency checks by default', async () => {
  let done!: (value: unknown) => void;
  h.Account.list.mockResolvedValue({ data: [{ stage: 'LEAD' }, { stage: 'CLIENT' }] });
  h.Quote.list.mockReturnValue(new Promise(resolve => { done = resolve; }));
  h.Policy.list.mockRejectedValue(new Error('Policy service unavailable'));
  render(<MemoryRouter><Overview /></MemoryRouter>);
  const accounts = within(screen.getByRole('region', { name: 'Account totals' }));
  expect(await accounts.findByText('Open leads')).toBeVisible();
  expect(within(screen.getByRole('region', { name: 'Quote totals' })).getByText('Loading…')).toBeVisible();
  expect(await screen.findByText('Policy service unavailable')).toBeVisible();
  expect(h.Invoice.list).not.toHaveBeenCalled(); expect(h.Document.list).not.toHaveBeenCalled();
  await act(async () => done({ data: [{ status: 'QUOTED' }] }));
  expect(screen.getByText('Quotes in flight')).toBeVisible();
  h.Policy.list.mockResolvedValue({ data: [] });
  fireEvent.click(within(screen.getByRole('region', { name: 'Policy totals' })).getByRole('button', { name: 'Try again' }));
  expect(await screen.findByText('Active policies')).toBeVisible();
});
