import { useEffect, useRef, useState } from "react";
import { uploadData, remove } from "aws-amplify/storage";
import {
  client,
  friendlyError,
  listAllPages,
  type CrmDocument,
  type Policy,
  type Quote,
} from "../lib/client";
import { downloadFile } from "../lib/storage";
import { useAsyncResource } from "../lib/useAsyncResource";
import {
  linkFields,
  linkKeyOf,
  matchesLink,
  policyLinkLabel,
  quoteLinkLabel,
} from "../lib/documentLinks";
import type { Schema } from "../../amplify/data/resource";
import FilePreviewModal, { canPreview } from "./FilePreview";
import FileButton from "./FileButton";
import ConfirmButton from "./ConfirmButton";
import { SaveStatus, useSaveStatus } from "./SaveStatus";
import { Badge, statusBadge, OCR_STATUS_BADGE } from "../lib/badges";
import { useSort, SortTh } from "../lib/useSort";
import { withExtension } from "../../amplify/functions/process-document/name";
import {
  DEFAULT_DOCUMENT_CATEGORY,
  DOCUMENT_CATEGORY_OPTIONS,
  type DocumentCategory as Category,
} from "../lib/enums";

type EntityType = Schema["DocumentEntityType"]["type"];

/**
 * The categories a human may pick, alphabetical by label. `ACORD_FORM` is
 * absent by design — those are generated by the forms tab, never uploaded —
 * and because this list doubles as the table's label lookup below, an ACORD
 * document shows no category. Both facts now live in `lib/enums.ts`, where the
 * exclusion is explicit rather than an omission that compiles.
 */
const CATEGORIES = DOCUMENT_CATEGORY_OPTIONS;

/**
 * Attach-to-anything documents panel: uploads to
 * documents/{entityType}/{entityId}/{documentId}/{filename}, which the
 * Textract Lambda watches. observeQuery keeps OCR status live in the UI.
 *
 * Names are editable. `name` is only ever a display string — it is captured
 * from the file at upload and is not the S3 key — so renaming is a plain
 * field update: the object does not move, the download URL does not change,
 * and nothing re-OCRs (the pipeline fires on `s3:ObjectCreated`, which a
 * DynamoDB write is not). The one invariant the edit has to hold is the
 * extension, because `canPreview` reads it off `name`; `withExtension` is
 * shared with the Lambda's auto-namer so both paths hold it the same way.
 */
export default function DocumentsPanel({
  entityType,
  entityId,
  linkAccountId,
  initialLink,
}: {
  entityType: EntityType;
  entityId: string;
  /**
   * When set (the ACCOUNT mount), documents can be linked to that account's
   * policies and quotes: the toolbar gains a "Linked to" view that both
   * filters the table and targets uploads, and each row gets a link select.
   * Carrier and license mounts leave it unset and change nothing.
   */
  linkAccountId?: string;
  /** A "policy:<id>" / "quote:<id>" key to open pre-filtered on. */
  initialLink?: string;
}) {
  const [docs, setDocs] = useState<CrmDocument[]>([]);
  /**
   * False until observeQuery's first COMPLETE snapshot. The initial sync
   * arrives in pages, and painting each page as it lands makes the table
   * assemble itself in front of the reader — worse, before any page lands
   * the panel claims "No documents attached." about an account it hasn't
   * finished reading. One flag holds the panel to: say nothing until you
   * know, then stay live.
   */
  const [docsSynced, setDocsSynced] = useState(false);
  const [category, setCategory] = useState<Category>(DEFAULT_DOCUMENT_CATEGORY);
  const [view, setView] = useState(
    initialLink && /^(policy|quote):.+$/.test(initialLink) ? initialLink : ""
  );

  /**
   * The link targets — every policy, every quote. Closed quotes and expired
   * policies stay listed: paper about a lost quote or a lapsed term is still
   * paper someone filed, and a target vanishing from the list must not make
   * its documents unreachable.
   */
  const linkTargets = useAsyncResource(
    async () => {
      if (!linkAccountId) return { options: [] as { key: string; label: string }[] };
      const [policies, quotes] = await Promise.all([
        listAllPages((nextToken) =>
          client.models.Policy.list({
            filter: { accountId: { eq: linkAccountId } },
            nextToken,
          })
        ),
        listAllPages((nextToken) =>
          client.models.Quote.list({
            filter: { accountId: { eq: linkAccountId } },
            nextToken,
          })
        ),
      ]);
      return {
        options: [
          ...(policies as Policy[]).map((p) => ({
            key: `policy:${p.id}`,
            label: policyLinkLabel(p),
          })),
          ...(quotes as Quote[]).map((q) => ({
            key: `quote:${q.id}`,
            label: quoteLinkLabel(q),
          })),
        ],
      };
    },
    [linkAccountId],
    { initialData: { options: [] } }
  );
  const linkOptions = linkTargets.data.options;
  const linkLabel = (key: string) =>
    linkOptions.find((o) => o.key === key)?.label ?? "(deleted record)";
  const [uploading, setUploading] = useState(false);
  const [error, setError] = useState("");
  const [openDocId, setOpenDocId] = useState<string | null>(null);
  const [renameId, setRenameId] = useState<string | null>(null);
  const [renameValue, setRenameValue] = useState("");
  // Auto-clearing: these are per-row actions with no form to go dirty and
  // retire the message — the deleted row is gone from the table entirely, and
  // the renamed one is back to plain text — so nothing on screen would ever
  // clear it.
  const rowStatus = useSaveStatus({ autoClearMs: 4000 });
  const [previewDoc, setPreviewDoc] = useState<CrmDocument | null>(null);
  const [ocrSearch, setOcrSearch] = useState("");
  const [matchIdx, setMatchIdx] = useState(0);
  const [matchCount, setMatchCount] = useState(0);
  const viewerRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    // A different entity is a different resource: back to pristine, so the
    // gate re-arms instead of leaving the previous mount's rows (or its
    // empty state) under the new one's heading.
    setDocs([]);
    setDocsSynced(false);
    const sub = client.models.Document.observeQuery({
      filter: { entityId: { eq: entityId } },
    }).subscribe({
      next: ({ items, isSynced }) => {
        // Snapshots before isSynced are partial pages of the initial read —
        // held back, the table appears once, complete. After sync, every
        // snapshot is a real change (an upload landing, an OCR status
        // flipping) and applies immediately; that liveness is the whole
        // reason this is a subscription and not a fetch.
        if (!isSynced) return;
        setDocs([...items]);
        setDocsSynced(true);
      },
    });
    return () => sub.unsubscribe();
  }, [entityId]);

  async function handleUpload(files: File[] | null) {
    if (!files?.length) return;
    setUploading(true);
    setError("");
    for (const file of files) {
      let docId: string | null = null;
      try {
        const { data: doc, errors } = await client.models.Document.create({
          entityType,
          entityId,
          category,
          name: file.name,
          s3Key: "pending",
          contentType: file.type,
          sizeBytes: file.size,
          ocrStatus: "PENDING",
          // Uploads land where the viewer is looking: the selected policy
          // or quote, or unlinked when viewing everything.
          ...(view ? linkFields(view) : {}),
        });
        if (errors?.length || !doc) throw new Error(errors?.[0]?.message);
        docId = doc.id;

        const path = `documents/${entityType}/${entityId}/${doc.id}/${file.name}`;
        await client.models.Document.update({ id: doc.id, s3Key: path });
        await uploadData({
          path,
          data: file,
          options: { contentType: file.type || undefined },
        }).result;
      } catch (err) {
        // Don't leave a ghost record behind for a file that never landed.
        if (docId) {
          await client.models.Document.delete({ id: docId }).catch(() => {});
        }
        setError(
          `"${file.name}" failed to upload — ${friendlyError(err, "unknown error")}`
        );
      }
    }
    setUploading(false);
  }

  async function download(doc: CrmDocument) {
    try {
      // `doc.name`, not the key: the row is renameable, and Downloads should
      // agree with what the row says.
      await downloadFile(doc.s3Key, { filename: doc.name });
    } catch (err) {
      setError(
        `"${doc.name}" couldn't be downloaded — ${friendlyError(err, "unknown error")}`
      );
    }
  }

  function startRename(doc: CrmDocument) {
    setRenameId(doc.id);
    // Seeded with the whole current name, extension included. Deleting it is
    // allowed — `withExtension` puts it back — but a producer editing
    // "scan_0043.pdf" should see what they are editing, not a stem.
    setRenameValue(doc.name);
    rowStatus.markDirty();
  }

  async function saveRename(doc: CrmDocument) {
    // The extension comes from the stored object, not from the name being
    // replaced: a name that has already been edited may no longer carry the
    // right one, and the key always does.
    const source = doc.s3Key && doc.s3Key !== "pending" ? doc.s3Key : doc.name;
    const name = withExtension(renameValue, source);
    if (!name) {
      rowStatus.markError("A document needs a name.");
      return;
    }
    setRenameId(null);
    if (name === doc.name) return;

    await rowStatus.run(
      async () => {
        const { errors } = await client.models.Document.update({
          id: doc.id,
          name,
        });
        if (errors?.length) throw new Error(errors[0].message);
      },
      {
        savedMessage: `Renamed to "${name}".`,
        errorMessage: "Couldn't rename that document.",
      }
    );
  }

  async function deleteDoc(doc: CrmDocument) {
    await rowStatus.run(
      async () => {
        if (doc.s3Key && doc.s3Key !== "pending") {
          await remove({ path: doc.s3Key }).catch(() => {});
        }
        // `errors` used to be dropped: the observeQuery subscription simply
        // kept the row, which reads as "the Confirm delete button missed".
        const { errors } = await client.models.Document.delete({ id: doc.id });
        if (errors?.length) throw new Error(errors[0].message);
      },
      {
        savedMessage: `"${doc.name}" deleted.`,
        errorMessage: "Couldn't delete that document.",
      }
    );
    // `run` never rejects, so <ConfirmButton> disarms either way — the same
    // unconditional close the hand-rolled confirm/keep pair did. The outcome
    // is reported by the panel's one SaveStatus line, not by the button.
  }

  async function relink(doc: CrmDocument, key: string) {
    await rowStatus.run(
      async () => {
        const { errors } = await client.models.Document.update({
          id: doc.id,
          ...linkFields(key),
        });
        if (errors?.length) throw new Error(errors[0].message);
      },
      {
        savedMessage: key
          ? `"${doc.name}" linked to ${linkLabel(key)}.`
          : `"${doc.name}" unlinked.`,
        errorMessage: "Couldn't change that link.",
      }
    );
  }

  function highlight(text: string, term: string) {
    if (!term.trim()) return text;
    const parts = text.split(new RegExp(`(${term.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")})`, "gi"));
    return parts.map((p, i) =>
      p.toLowerCase() === term.toLowerCase() ? <mark key={i}>{p}</mark> : p
    );
  }

  // The chosen link filters the table — "you are looking at this policy's
  // documents" — and everything when nothing is chosen.
  const visible = linkAccountId ? docs.filter((d) => matchesLink(d, view)) : docs;

  // Most recently uploaded first, as the subscription used to order them.
  const { sorted, sortKey, dir, toggle } = useSort(
    visible,
    {
      name: (d) => d.name,
      category: (d) => CATEGORIES.find((c) => c.value === d.category)?.label,
      linked: (d) => (linkKeyOf(d) ? linkLabel(linkKeyOf(d)) : null),
      // Sorts on the words in the badge, so the column orders the way it reads.
      ocr: (d) =>
        statusBadge(OCR_STATUS_BADGE, d.ocrStatus, OCR_STATUS_BADGE.PENDING).label,
      size: (d) => d.sizeBytes,
      created: (d) => d.createdAt,
    },
    "created",
    "desc"
  );

  const openDoc = docs.find((d) => d.id === openDocId);
  const openTables = openDoc ? parseTables(openDoc.ocrTables) : null;

  // Ctrl+F-style match navigation: after each render, index the <mark>
  // elements (text + tables, DOM order), flag the current one, scroll to it.
  useEffect(() => {
    const container = viewerRef.current;
    if (!container) {
      if (matchCount !== 0) setMatchCount(0);
      return;
    }
    const marks = container.querySelectorAll("mark");
    if (marks.length !== matchCount) setMatchCount(marks.length);
    marks.forEach((m) => m.classList.remove("ocr-current"));
    if (marks.length > 0) {
      const idx = ((matchIdx % marks.length) + marks.length) % marks.length;
      const current = marks[idx];
      current.classList.add("ocr-current");
      current.scrollIntoView({ block: "nearest" });
    }
  }, [ocrSearch, matchIdx, openDocId, matchCount, openTables]);

  function stepMatch(delta: number) {
    if (matchCount === 0) return;
    setMatchIdx((i) => (((i + delta) % matchCount) + matchCount) % matchCount);
  }

  return (
    <div>
      <div className="toolbar">
        {linkAccountId && (
          <div className="field">
            <label>Linked to</label>
            {/* One control, two jobs on purpose: it filters the table AND
                targets uploads — "you are looking at this policy's
                documents; files you attach here belong to it". */}
            <select value={view} onChange={(e) => setView(e.target.value)}>
              <option value="">Everything</option>
              {linkOptions.map((o) => (
                <option key={o.key} value={o.key}>
                  {o.label}
                </option>
              ))}
            </select>
          </div>
        )}
        <div className="field">
          <label>Category</label>
          <select
            value={category}
            onChange={(e) => setCategory(e.target.value as Category)}
          >
            {CATEGORIES.map((c) => (
              <option key={c.value} value={c.value}>
                {c.label}
              </option>
            ))}
          </select>
        </div>
        <div className="field">
          <label>Attach files (PDF/images are OCR'd automatically)</label>
          <FileButton
            label="Choose files…"
            multiple
            busy={uploading}
            onFiles={handleUpload}
          />
        </div>
        {error && <span className="error-text">{error}</span>}
        {/* Renames and deletes are per-row with no per-row place to report;
            this is the panel's one status line. */}
        <SaveStatus {...rowStatus.status} />
      </div>

      {!docsSynced ? (
        <p className="muted small">Loading…</p>
      ) : visible.length === 0 ? (
        <p className="muted small">
          {view
            ? `Nothing linked to ${linkLabel(view)} yet — files attached while it's selected will be.`
            : "No documents attached."}
        </p>
      ) : (
        <div className="table-wrap">
          <table>
            <thead>
              <tr>
                <SortTh label="Name" colKey="name" sortKey={sortKey} dir={dir} onToggle={toggle} />
                <SortTh label="Category" colKey="category" sortKey={sortKey} dir={dir} onToggle={toggle} />
                {linkAccountId && (
                  <SortTh label="Linked to" colKey="linked" sortKey={sortKey} dir={dir} onToggle={toggle} />
                )}
                <SortTh label="OCR" colKey="ocr" sortKey={sortKey} dir={dir} onToggle={toggle} />
                <SortTh label="Size" colKey="size" sortKey={sortKey} dir={dir} onToggle={toggle} />
                <th></th>
              </tr>
            </thead>
            <tbody>
              {sorted.map((d) => {
                // No OCR status yet, or one this table doesn't know, both read
                // as "queued" — the state a document is in before the Textract
                // Lambda has said anything about it.
                const badge = statusBadge(
                  OCR_STATUS_BADGE,
                  d.ocrStatus,
                  OCR_STATUS_BADGE.PENDING
                );
                const renaming = renameId === d.id;
                return (
                  <tr key={d.id}>
                    <td>
                      {renaming ? (
                        <div className="field">
                          <input
                            aria-label="Document name"
                            autoFocus
                            value={renameValue}
                            onChange={(e) => setRenameValue(e.target.value)}
                            onKeyDown={(e) => {
                              if (e.key === "Enter") void saveRename(d);
                              if (e.key === "Escape") setRenameId(null);
                            }}
                          />
                        </div>
                      ) : (
                        d.name
                      )}
                    </td>
                    <td>
                      <span className="badge gray">
                        {CATEGORIES.find((c) => c.value === d.category)?.label ?? "—"}
                      </span>
                    </td>
                    {linkAccountId && (
                      <td>
                        {/* Editable in place, like the status selects on the
                            policy rows: linking existing paper is the whole
                            point — a scan often arrives before the policy
                            it belongs to exists. */}
                        <select
                          aria-label={`Link ${d.name}`}
                          value={linkKeyOf(d)}
                          onChange={(e) => void relink(d, e.target.value)}
                        >
                          <option value="">—</option>
                          {linkOptions.map((o) => (
                            <option key={o.key} value={o.key}>
                              {o.label}
                            </option>
                          ))}
                          {linkKeyOf(d) &&
                            !linkOptions.some((o) => o.key === linkKeyOf(d)) && (
                              <option value={linkKeyOf(d)}>(deleted record)</option>
                            )}
                        </select>
                      </td>
                    )}
                    <td>
                      <Badge {...badge} />
                      {d.ocrStatus === "FAILED" && d.ocrError && (
                        <div className="muted small">{d.ocrError}</div>
                      )}
                    </td>
                    <td className="muted small">
                      {d.sizeBytes ? `${Math.max(1, Math.round(d.sizeBytes / 1024))} KB` : "—"}
                    </td>
                    <td style={{ whiteSpace: "nowrap" }}>
                      {/* While a row is being renamed its other actions are
                          hidden rather than disabled: Preview and Download
                          would still work, but leaving them there invites a
                          click that discards the edit without saying so. */}
                      {renaming ? (
                        <>
                          <button
                            className="link"
                            onClick={() => void saveRename(d)}
                          >
                            Save name
                          </button>
                          <button
                            className="link"
                            onClick={() => setRenameId(null)}
                          >
                            Cancel
                          </button>
                        </>
                      ) : (
                        <>
                          <button
                            className="link"
                            onClick={() => startRename(d)}
                          >
                            Rename
                          </button>
                          {d.s3Key !== "pending" && canPreview(d.name) && (
                            <button
                              className="link"
                              onClick={() => setPreviewDoc(d)}
                            >
                              Preview
                            </button>
                          )}
                          <button className="link" onClick={() => download(d)}>
                            Download
                          </button>
                          {d.ocrStatus === "COMPLETE" && d.ocrText && (
                            <button
                              className="link"
                              onClick={() =>
                                setOpenDocId(openDocId === d.id ? null : d.id)
                              }
                            >
                              {openDocId === d.id ? "Hide text" : "View text"}
                            </button>
                          )}
                          <ConfirmButton
                            confirmLabel="Confirm delete"
                            cancelLabel="Keep"
                            onConfirm={() => deleteDoc(d)}
                          />
                        </>
                      )}
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      )}

      {previewDoc && (
        <FilePreviewModal
          s3Key={previewDoc.s3Key}
          name={previewDoc.name}
          onClose={() => setPreviewDoc(null)}
        />
      )}

      {openDoc?.ocrText && (
        <div style={{ marginTop: 14 }} ref={viewerRef}>
          <h3>Extracted text — {openDoc.name}</h3>
          <div className="ocr-search field">
            <div className="ocr-find">
              <input
                placeholder="Find in text…"
                value={ocrSearch}
                onChange={(e) => {
                  setOcrSearch(e.target.value);
                  setMatchIdx(0);
                }}
                onKeyDown={(e) => {
                  if (e.key === "Enter") stepMatch(e.shiftKey ? -1 : 1);
                }}
              />
              {ocrSearch.trim() && (
                <>
                  <span className="ocr-count">
                    {matchCount === 0 ? "0 results" : `${(matchIdx % matchCount + matchCount) % matchCount + 1} of ${matchCount}`}
                  </span>
                  <button
                    className="secondary"
                    title="Previous match (Shift+Enter)"
                    disabled={matchCount === 0}
                    onClick={() => stepMatch(-1)}
                  >
                    ▲
                  </button>
                  <button
                    className="secondary"
                    title="Next match (Enter)"
                    disabled={matchCount === 0}
                    onClick={() => stepMatch(1)}
                  >
                    ▼
                  </button>
                </>
              )}
            </div>
          </div>
          <div className="ocr-text">{highlight(openDoc.ocrText, ocrSearch)}</div>

          {openTables && openTables.length > 0 && (
            <>
              <h3>
                Extracted tables ({openTables.length}) — budgets, dues
                schedules, etc.
              </h3>
              {openTables.map((table, ti) => (
                <div className="table-wrap ocr-table" key={ti}>
                  <table>
                    <tbody>
                      {table.map((row, ri) => (
                        <tr key={ri}>
                          {row.map((cell, ci) => (
                            <td key={ci}>{highlight(cell, ocrSearch)}</td>
                          ))}
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              ))}
            </>
          )}
        </div>
      )}
    </div>
  );
}

/**
 * ocrTables is an AWSJSON field written as a JSON string by the Lambda, so
 * it may come back single- or double-encoded depending on the write path.
 */
function parseTables(raw: unknown): string[][][] | null {
  let v: unknown = raw;
  try {
    if (typeof v === "string") v = JSON.parse(v);
    if (typeof v === "string") v = JSON.parse(v);
  } catch {
    return null;
  }
  return Array.isArray(v) && v.length ? (v as string[][][]) : null;
}
