import { act, fireEvent, render, screen } from "@testing-library/react";
import { beforeEach, expect, it, vi } from "vitest";
const h = vi.hoisted(() => ({ request: vi.fn(), resource: { loading: false, loaded: true, error: "", data: { entries: {}, team: [] }, refetch: vi.fn(), setData: vi.fn() } }));
vi.mock("../lib/commercial", () => ({ useCommercial: () => h.resource }));
vi.mock("../lib/communications", () => ({ communicationRequest: h.request }));
vi.mock("../lib/client", () => ({ LINES_OF_BUSINESS: ["Property"], fmtMoney: (v: number) => `$${v}` }));
vi.mock("./OpportunityEstimate", () => ({ OpportunityEstimate: () => null }));
import QuotePackages from "./QuotePackages";
import { emptyCommercialPlan } from "../../../shared/quotePackages";
beforeEach(() => { vi.clearAllMocks(); h.resource.loading = false; h.resource.loaded = true; h.resource.error = ""; });
it("retains a package draft through refresh and account navigation resets it", async () => {
  const view = render(<QuotePackages accountId="a1" quotes={[]} carriers={[]} />);
  fireEvent.click(screen.getByRole("button", { name: "+ Package option" }));
  fireEvent.change(screen.getByLabelText("Option name"), { target: { value: "Local package draft" } });
  h.resource.loading = true;
  view.rerender(<QuotePackages accountId="a1" quotes={[]} carriers={[]} />);
  expect(screen.getByLabelText("Option name")).toHaveValue("Local package draft");
  h.resource.loading = false;
  view.rerender(<QuotePackages accountId="a2" quotes={[]} carriers={[]} />);
  expect(screen.queryByLabelText("Option name")).toBeNull();
});
it("locks draft fields while saving and preserves them if the write fails", async () => {
  let fail!: (error: Error) => void;
  h.request.mockImplementation(() => new Promise((_resolve, reject) => { fail = reject; }));
  render(<QuotePackages accountId="a1" quotes={[]} carriers={[]} />);
  fireEvent.click(screen.getByRole("button", { name: "+ Package option" }));
  fireEvent.change(screen.getByLabelText("Option name"), { target: { value: "Reviewed package" } });
  fireEvent.submit(screen.getByRole("form", { name: "Edit package option" }));
  fireEvent.submit(screen.getByRole("form", { name: "Edit package option" }));
  expect(h.request).toHaveBeenCalledTimes(1);
  expect(screen.getByLabelText("Option name")).toBeDisabled();
  await act(async () => fail(new Error("Version changed; review current package")));
  expect(screen.getByRole("alert")).toHaveTextContent("Version changed");
  expect(screen.getByLabelText("Option name")).toHaveValue("Reviewed package");
  expect(screen.getByLabelText("Option name")).toBeEnabled();
  h.request.mockResolvedValue({ plan: emptyCommercialPlan("a1") });
  fireEvent.submit(screen.getByRole("form", { name: "Edit package option" }));
  await act(async () => {});
  expect(screen.queryByRole("form")).toBeNull();
});
