import { useState } from "react";
import type { LeadTask, TeamEligibility } from "../../../shared/leadWorkflow";
import { BLOCKER_REASONS } from "../../../shared/workBlocker";
import { fmtDateTime } from "../lib/client";

export default function WorkBlocker({ task, team, busy, run }: { task: LeadTask; team: TeamEligibility[]; busy: boolean; run: (op: string, input: unknown) => Promise<boolean> }) {
  const [editing, setEditing] = useState(false), [reason, setReason] = useState<string>(BLOCKER_REASONS[0]), [owner, setOwner] = useState(""), [detail, setDetail] = useState("");
  const submit = async (action: string) => { if (await run("updateBlocker", { taskId: task.id, version: task.version, action, reason, ownerId: owner, detail })) setEditing(false); };
  if (task.blocker) return <div className="workflow-notice"><strong>Blocked: {task.blocker.reason}</strong><p className="small">Owner: {team.find(t => t.userId === task.blocker!.ownerId)?.name ?? "Needs assignment"} · Review {fmtDateTime(task.blocker.reviewAt)}</p>{task.blocker.detail && <p>{task.blocker.detail}</p>}<div className="toolbar"><button className="secondary" disabled={busy} onClick={() => void submit("CLEAR")}>Blocker resolved</button><button className="link" disabled={busy} onClick={() => void submit("REVIEW")}>Still waiting</button></div><p className="small muted">Still waiting schedules the next business morning's review. The original deadline and client updates stay tracked. Resolving the blocker does not mark the work complete.</p></div>;
  return <details open={editing} onToggle={e => setEditing(e.currentTarget.open)}><summary>Something blocking this work?</summary><label className="field">Blocker<select value={reason} onChange={e => setReason(e.target.value)}>{BLOCKER_REASONS.map(r => <option key={r}>{r}</option>)}</select></label><label className="field">Who will help resolve it?<select value={owner} onChange={e => setOwner(e.target.value)}><option value="">Responsible manager</option>{team.filter(t => t.enabled).map(t => <option key={t.userId} value={t.userId}>{t.name}</option>)}</select></label><label className="field">Helpful detail (optional)<input maxLength={500} value={detail} onChange={e => setDetail(e.target.value)} /></label><p className="small muted">Reviewed at 9 a.m. the next business day. The original deadline and client updates stay tracked.</p><button className="secondary" disabled={busy} onClick={() => void submit("SET")}>Record blocker</button></details>;
}
